name: Deploy Demo Solution
on:
  workflow_dispatch:
    inputs:
      environment:
          description: 'Deploy to Environment'
          required: true
          default: 'dev'
          type: choice
          options:
          - dev
          - test
          - stage
          - prod
      reactVersionTag:
        description: 'React version tag to deploy'
        required: true
      dotNetVersionTag:
        description: '.NET version tag to deploy'
        required: true

jobs:
  trigger-dotnet-workflow:
    runs-on: ubuntu-latest
    outputs:
      workflow_run_id: ${{ steps.trigger_workflow.outputs.workflow_run_id }}
    steps:
      - name: Trigger Deployment of .NET Project Workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/danny-comeau-pm/demo-dotNet-project/actions/workflows/deploy-version.yml/dispatches
          ref: main
          inputs: '{"environment":"${{ github.event.inputs.environment }}","versionTag":"${{ github.event.inputs.dotNetVersionTag }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.deployment_token }}
  
  trigger-react-workflow:
    needs: trigger-dotnet-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment of React Project Workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/danny-comeau-pm/demo-project/actions/workflows/deploy-version.yml/dispatches
          ref: main
          inputs: '{"environment":"${{ github.event.inputs.environment }}","versionTag":"${{ github.event.inputs.reactVersionTag }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.deployment_token }}
