name: Deploy Demo Solution
on:
  workflow_dispatch:
    inputs:
      environment:
          description: 'Deploy to Environment'
          required: true
          default: 'dev'
          type: choice
          options:
          - dev
          - test
          - stage
          - prod
      reactVersionTag:
        description: 'React version tag to deploy'
        required: true
      dotNetVersionTag:
        description: '.NET version tag to deploy'
        required: true

jobs:
  trigger-dotnet-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment of .NET Project Workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: danny-comeau-pm
          repo: demo-dotNet-project
          workflow_id: deploy-version.yml
          # ref: main
          inputs: '{"environment":"${{ github.event.inputs.environment }}","versionTag":"${{ github.event.inputs.dotNetVersionTag }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.deployment_token }}
  
  trigger-react-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment of React Project Workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: danny-comeau-pm
          repo: demo-project
          workflow_id: deploy-version.yml
          # ref: main
          inputs: '{"environment":"${{ github.event.inputs.environment }}","versionTag":"${{ github.event.inputs.reactVersionTag }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.deployment_token }}
